const fs = require('fs');
const path = require('path');
const ffmpeg = require('fluent-ffmpeg');
const PDFDocument = require('pdfkit');
const QRCode = require('qrcode');
const config = require('../../config');

const TEMP_DIR = path.join(__dirname, '../../../temp');

function ensureTemp() {
  if (!fs.existsSync(TEMP_DIR)) fs.mkdirSync(TEMP_DIR, { recursive: true });
}

// -------------------- Sticker --------------------

async function createSticker(mediaBuffer, isVideo) {
  ensureTemp();

  const stamp = Date.now();
  const inputExt = isVideo ? 'mp4' : 'jpg';
  const inputPath = path.join(TEMP_DIR, `sticker_input_${stamp}.${inputExt}`);
  const outputPath = path.join(TEMP_DIR, `sticker_output_${stamp}.webp`);

  fs.writeFileSync(inputPath, mediaBuffer);

  try {
    await new Promise((resolve, reject) => {
      const cmd = ffmpeg(inputPath);

      if (isVideo) cmd.inputOptions(['-frames:v 1']);

      cmd
        .outputOptions([
          '-vf', 'scale=512:512:force_original_aspect_ratio=increase,crop=512:512',
          '-lossless', '0',
          '-quality', '75',
          '-compression_level', '6'
        ])
        .output(outputPath)
        .on('end', resolve)
        .on('error', reject)
        .run();
    });

    return fs.readFileSync(outputPath);
  } finally {
    try { if (fs.existsSync(inputPath)) fs.unlinkSync(inputPath); } catch {}
    try { if (fs.existsSync(outputPath)) fs.unlinkSync(outputPath); } catch {}
  }
}

// -------------------- Compression --------------------

async function compressImage(inputBuffer) {
  ensureTemp();

  const stamp = Date.now();
  const inputPath = path.join(TEMP_DIR, `img_in_${stamp}.jpg`);
  const outputPath = path.join(TEMP_DIR, `img_out_${stamp}.jpg`);

  fs.writeFileSync(inputPath, inputBuffer);

  try {
    await new Promise((resolve, reject) => {
      ffmpeg(inputPath)
        .outputOptions(['-q:v 30', '-compression_level 6'])
        .output(outputPath)
        .on('end', resolve)
        .on('error', reject)
        .run();
    });

    return fs.readFileSync(outputPath);
  } finally {
    try { if (fs.existsSync(inputPath)) fs.unlinkSync(inputPath); } catch {}
    try { if (fs.existsSync(outputPath)) fs.unlinkSync(outputPath); } catch {}
  }
}

async function compressVideo(inputBuffer) {
  ensureTemp();

  const stamp = Date.now();
  const inputPath = path.join(TEMP_DIR, `vid_in_${stamp}.mp4`);
  const outputPath = path.join(TEMP_DIR, `vid_out_${stamp}.mp4`);

  fs.writeFileSync(inputPath, inputBuffer);

  try {
    await new Promise((resolve, reject) => {
      ffmpeg(inputPath)
        .videoCodec('libx264')
        .audioCodec('aac')
        .outputOptions(['-crf 28', '-preset faster', '-vf scale=640:-2'])
        .output(outputPath)
        .on('end', resolve)
        .on('error', reject)
        .run();
    });

    return fs.readFileSync(outputPath);
  } finally {
    try { if (fs.existsSync(inputPath)) fs.unlinkSync(inputPath); } catch {}
    try { if (fs.existsSync(outputPath)) fs.unlinkSync(outputPath); } catch {}
  }
}

// -------------------- PDF --------------------

async function imageToPdf(imageBuffer) {
  ensureTemp();

  const stamp = Date.now();
  const imagePath = path.join(TEMP_DIR, `pdf_${stamp}.jpg`);
  fs.writeFileSync(imagePath, imageBuffer);

  try {
    const doc = new PDFDocument({ size: 'A4', margin: 20 });
    const chunks = [];

    const finished = new Promise((resolve, reject) => {
      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);
    });

    try {
      doc.image(imagePath, { fit: [500, 700], align: 'center', valign: 'center' });
    } catch (err) {
      doc.fontSize(14).text('Image could not be embedded.', { align: 'center' });
    }

    doc.fontSize(10)
      .fillColor('#888888')
      .text(
        `Generated by ${config.botName} • ${new Date().toLocaleDateString()}`,
        20,
        doc.page.height - 30
      );

    doc.end();
    return await finished;
  } finally {
    try { if (fs.existsSync(imagePath)) fs.unlinkSync(imagePath); } catch {}
  }
}

async function textToPdf(text) {
  const doc = new PDFDocument({ size: 'A4', margin: 50 });
  const chunks = [];

  const finished = new Promise((resolve, reject) => {
    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
  });

  doc.fontSize(20).font('Helvetica-Bold').text('Document', { align: 'center' });
  doc.moveDown(2);
  doc.fontSize(10).font('Helvetica').text(`Generated: ${new Date().toLocaleString()}`, { align: 'right' });
  doc.moveDown();
  doc.moveTo(50, doc.y).lineTo(doc.page.width - 50, doc.y).stroke();
  doc.moveDown();

  doc.fontSize(12).font('Helvetica').text(text, {
    align: 'left',
    lineGap: 8,
    paragraphGap: 10,
    indent: 20,
    width: doc.page.width - 100
  });

  doc.fontSize(10).fillColor('#666666').text(
    `Generated by ${config.botName} • Page ${doc.page.number}`,
    50,
    doc.page.height - 30,
    { align: 'center', width: doc.page.width - 100 }
  );

  doc.end();
  return await finished;
}

// -------------------- View-once reveal --------------------

async function revealAndSend(sock, chatJid, mediaBuffer, isVideo, quotedMsg) {
  if (isVideo) {
    return sock.sendMessage(chatJid, { video: mediaBuffer }, { quoted: quotedMsg });
  }
  return sock.sendMessage(chatJid, { image: mediaBuffer }, { quoted: quotedMsg });
}

// -------------------- QR code --------------------

async function generateQrCode(text) {
  return QRCode.toBuffer(text, {
    width: 300,
    margin: 2,
    color: {
      dark: '#000000',
      light: '#FFFFFF'
    }
  });
}

module.exports = {
  createSticker,
  compressImage,
  compressVideo,
  imageToPdf,
  textToPdf,
  revealAndSend,
  generateQrCode
};