const fs = require('fs');
const path = require('path');
const PDFDocument = require('pdfkit');
const config = require('../../config');

// Builds PDFs from images or raw text.

const TEMP_DIR = path.join(__dirname, '../../../temp');

async function imageToPdf(imageBuffer) {
  if (!fs.existsSync(TEMP_DIR)) fs.mkdirSync(TEMP_DIR, { recursive: true });

  const stamp = Date.now();
  const imagePath = path.join(TEMP_DIR, `pdf_${stamp}.jpg`);
  fs.writeFileSync(imagePath, imageBuffer);

  try {
    const doc = new PDFDocument({ size: 'A4', margin: 20 });
    const chunks = [];

    const finished = new Promise((resolve, reject) => {
      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);
    });

    try {
      doc.image(imagePath, { fit: [500, 700], align: 'center', valign: 'center' });
    } catch (err) {
      doc.fontSize(14).text('Image could not be embedded.', { align: 'center' });
    }

    doc.fontSize(10)
      .fillColor('#888888')
      .text(
        `Generated by ${config.botName} • ${new Date().toLocaleDateString()}`,
        20,
        doc.page.height - 30
      );

    doc.end();
    return await finished;
  } finally {
    try { if (fs.existsSync(imagePath)) fs.unlinkSync(imagePath); } catch {}
  }
}

async function textToPdf(text) {
  const doc = new PDFDocument({ size: 'A4', margin: 50 });
  const chunks = [];

  const finished = new Promise((resolve, reject) => {
    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
  });

  doc.fontSize(20).font('Helvetica-Bold').text('Document', { align: 'center' });
  doc.moveDown(2);
  doc.fontSize(10).font('Helvetica').text(`Generated: ${new Date().toLocaleString()}`, { align: 'right' });
  doc.moveDown();
  doc.moveTo(50, doc.y).lineTo(doc.page.width - 50, doc.y).stroke();
  doc.moveDown();

  doc.fontSize(12).font('Helvetica').text(text, {
    align: 'left',
    lineGap: 8,
    paragraphGap: 10,
    indent: 20,
    width: doc.page.width - 100
  });

  doc.fontSize(10).fillColor('#666666').text(
    `Generated by ${config.botName} • Page ${doc.page.number}`,
    50,
    doc.page.height - 30,
    { align: 'center', width: doc.page.width - 100 }
  );

  doc.end();
  return await finished;
}

module.exports = { imageToPdf, textToPdf };