const fs = require('fs');
const path = require('path');
const PDFDocument = require('pdfkit');

class PDFGenerator {
  constructor(sock) {
    this.sock = sock;
  }
  
  async imageToPdf(sender, userJid, msg, config) {
    let processingMsg;
    try {
      const quotedMsg = msg.message?.extendedTextMessage?.contextInfo?.quotedMessage;
      const hasImage = msg.message?.imageMessage || (quotedMsg && quotedMsg.imageMessage);
      
      if (!hasImage) {
        await this.sock.sendMessage(sender, {
          text: `❌ Reply to an image!`
        }, { quoted: msg });
        return;
      }
      
      processingMsg = await this.sock.sendMessage(sender, {
        text: '📄 *Converting image to PDF...*'
      });
      
      const messageToDownload = quotedMsg ? { message: quotedMsg } : msg;
      const downloadedData = await this.sock.downloadMediaMessage(messageToDownload);
      
      const imageBuffer = await this.ensureBuffer(downloadedData);
      
      if (!imageBuffer || imageBuffer.length === 0) {
        throw new Error('Downloaded image is empty');
      }
      
      const tempDir = './temp';
      if (!fs.existsSync(tempDir)) {
        fs.mkdirSync(tempDir, { recursive: true });
      }
      
      const timestamp = Date.now();
      const tempImagePath = path.join(tempDir, `notes_${timestamp}.jpg`);
      
      fs.writeFileSync(tempImagePath, imageBuffer);
      
      const doc = new PDFDocument({
        size: 'A4',
        margin: 20
      });
      
      const pdfChunks = [];
      doc.on('data', chunk => pdfChunks.push(chunk));
      
      const pdfPromise = new Promise((resolve, reject) => {
        doc.on('end', () => {
          try {
            const pdfBuffer = Buffer.concat(pdfChunks);
            resolve(pdfBuffer);
          } catch (error) {
            reject(error);
          }
        });
        doc.on('error', reject);
      });
      
      try {
        doc.image(tempImagePath, {
          fit: [500, 700],
          align: 'center',
          valign: 'center'
        });
      } catch (imageError) {
        console.error('PDFKit image error:', imageError);
        doc.fontSize(16).text('Image to PDF', { align: 'center' });
        doc.moveDown();
        doc.fontSize(12).text('⚠️ Image format not supported', { align: 'center' });
        doc.moveDown();
        doc.text('Try using JPEG format', { align: 'center' });
      }
      
      doc.fontSize(10)
         .fillColor('#888888')
         .text(`Generated by ${config.botName} • ${new Date().toLocaleDateString()}`, 
               20, doc.page.height - 30);
      
      doc.end();
      
      const pdfBuffer = await pdfPromise;
      
      try {
        if (fs.existsSync(tempImagePath)) {
          fs.unlinkSync(tempImagePath);
        }
      } catch (cleanupError) {
        console.error('Cleanup error:', cleanupError);
      }
      
      await this.sock.sendMessage(sender, {
        document: pdfBuffer,
        fileName: `school_notes_${timestamp}.pdf`,
        mimetype: 'application/pdf',
        caption: '✅ Image converted to PDF'
      });
      
    } catch (error) {
      console.error('Image to PDF error:', error);
      await this.sock.sendMessage(sender, {
        text: `❌ Conversion failed: ${error.message}`
      });
    } finally {
      try {
        if (processingMsg && processingMsg.key) {
          await this.sock.sendMessage(sender, { delete: processingMsg.key });
        }
      } catch (e) {
        console.error('Error deleting message:', e);
      }
    }
  }
  
  async textToPdf(sender, userJid, msg, text, config) {
    try {
      const processingMsg = await this.sock.sendMessage(sender, {
        text: '📄 *Creating PDF from text...*'
      });
      
      const doc = new PDFDocument({
        size: 'A4',
        margin: 50
      });
      
      const pdfChunks = [];
      doc.on('data', chunk => pdfChunks.push(chunk));
      
      const pdfPromise = new Promise((resolve, reject) => {
        doc.on('end', () => {
          try {
            const pdfBuffer = Buffer.concat(pdfChunks);
            resolve(pdfBuffer);
          } catch (error) {
            reject(error);
          }
        });
        doc.on('error', reject);
      });
      
      doc.fontSize(20)
         .font('Helvetica-Bold')
         .text('Document', { align: 'center' });
      
      doc.moveDown();
      doc.moveDown();
      
      doc.fontSize(10)
         .font('Helvetica')
         .text(`Generated: ${new Date().toLocaleString()}`, { align: 'right' });
      
      doc.moveDown();
      
      doc.moveTo(50, doc.y)
         .lineTo(doc.page.width - 50, doc.y)
         .stroke();
      
      doc.moveDown();
      
      doc.fontSize(12)
         .font('Helvetica')
         .text(text, {
           align: 'left',
           lineGap: 8,
           paragraphGap: 10,
           indent: 20,
           width: doc.page.width - 100
         });
      
      doc.moveDown();
      doc.moveDown();
      
      doc.fontSize(10)
         .fillColor('#666666')
         .text(`Generated by ${config.botName} • Page ${doc.page.number}`, 
               50, doc.page.height - 30, {
                 align: 'center',
                 width: doc.page.width - 100
               });
      
      doc.end();
      
      const pdfBuffer = await pdfPromise;
      
      await this.sock.sendMessage(sender, {
        document: pdfBuffer,
        fileName: `text_${Date.now()}.pdf`,
        mimetype: 'application/pdf',
        caption: '✅ Text converted to PDF'
      });
      
      try {
        if (processingMsg && processingMsg.key) {
          await this.sock.sendMessage(sender, { delete: processingMsg.key });
        }
      } catch (e) {}
      
    } catch (error) {
      console.error('Text to PDF error:', error);
      await this.sock.sendMessage(sender, {
        text: `❌ Error creating PDF: ${error.message}\n\nTry with shorter text or check your input.`
      });
    }
  }
  
  async ensureBuffer(data) {
    if (Buffer.isBuffer(data)) {
      return data;
    } else if (data && typeof data.pipe === 'function') {
      return await this.streamToBuffer(data);
    } else if (typeof data === 'string') {
      return Buffer.from(data);
    }
    throw new Error('Unsupported data type');
  }
  
  async streamToBuffer(stream) {
    return new Promise((resolve, reject) => {
      const chunks = [];
      stream.on('data', chunk => chunks.push(chunk));
      stream.on('end', () => resolve(Buffer.concat(chunks)));
      stream.on('error', reject);
    });
  }
}

module.exports = PDFGenerator;